### ISSUE TITLE
Team indication

### ISSUE THREAD

**Issue by Ziboo** [Ryan6578/TTS-Codenames#59]
Hello,

I'm kind of new to TTS, so I don't know if the list of players on the right in built in, 
but it would be nice to have a UI element that says who's in on what team.

Since it's random, you always have to rotate the view to see who it is, also need to know the color of the player to make sure everyone marked a clue

Thanks

**Comment by Ryan6578** [comment]
I think this needs more thought. How would you propose this exactly? I don't want to put people on a team (TTS team - diamonds/clubs/spades/etc), because then they would just use team chat the entire time. I want to foster open discussion and communication between the teams. I want people to have fun. I made it so that when you join a team that it more clearly indicates (with big bold letters) which team you're on. I know you won't be able to tell your teammates from this, but at least you, personally, would know when your turn is.

**Comment by Ryan6578** [comment]
I also want to restrict the amount of UI elements on someone's screen. I don't think people want to have their screens littered with UI elements for information they only really need once.
